### ISSUE TITLE
Make .github Private

### ISSUE THREAD

**Issue by cpqoc** [QOC-Innovations/.github#7]
I was looking through our users and it seems like `External Contributors` have access to some of our repositories including `.github`

The Other repos don't seem to contain anything too important (demos I think)

![Image](https://github.com/user-attachments/assets/bb4888dd-35d5-44c6-8fdc-9f95a4fd8c35)

### We need to be careful as I don't know what will happen if we make `.github` private

**Comment by bpqoc** [comment]
We have to keep the repo public, otherwise any templates for things like pull requests stop working for other repos in the organization.
